version: '3'

services:
    web:
        image: nginx:1.11.9
        ports:
            - "${EXTERNAL_PORT:-80}:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www:ro
    php:
        build: docker/php
        volumes:
            - .:/var/www
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: symfony
            DB_PASSWORD: symfony
            DB_NAME: symfony
    db:
        image: postgres
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
            POSTGRES_DB: symfony
