<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Agency;
use Doctrine\ORM\EntityRepository;

/**
 * AgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastAgencyPersisted() {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('agency')
            ->from(Agency::class, 'agency')
            ->orderBy('agency.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
