<?php

namespace AppBundle\Repository;

/**
 * AssociateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociateRepository extends \Doctrine\ORM\EntityRepository
{
}
