app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
