services:
    app.admin.agency:
        class: AppBundle\Admin\AgencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Agency" }
        arguments:
            - ~
            - AppBundle\Entity\Agency
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true

    app.admin.associate:
        class: AppBundle\Admin\AssociateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Associate" }
        arguments:
            - ~
            - AppBundle\Entity\Associate
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true
